# coding: utf-8

# flake8: noqa
"""
    BRP Berichten API

    Een REST API voor het a-synchroon uitwisselen van berichten welke in het Logisch Ontwerp gedefinieerd zijn.  # Wijzigingshistorie:  ## 0.6.2 Januari 2025 - OAuth endpoint demo omgeving gecorrigeerd.  ## 0.6.1 Januari 2025 - Ping endpoints zijn niet langer bereikbaar zonder eerst te authenticeren.  ## 0.6.0 Januari 2025 - Servers toegevoegd.   - Hiervoor moesten de paden van de endpoints aangepast worden. Hierdoor is '/api/v1' komen te vervallen bij de endpoints. Dit is verhuist naar de base-url's van de genoemde servers. - Authenticatie details toegevoegd. - Foutmeldingen bij het conversie endpoint bijgewerkt. - Alle namespace paden van de foutmeldingen nagelopen en gecorrigeerd daar waar nodig. Dit zodat ze consistent starten met: \"https://www.rvig.nl/brp/berichten-api/probleem/\".  ## 0.5.5 November 2024 - 'berichtVolgnummer' en 'afzender' required gemaakt in ListMessageKenmerken (en daardoor ook in GetMessageKenmerken). - De GET en DELETE foutsituaties zijn voorzien van discriminators ten behoeve van het onderscheiden van foutsituatie subtypes door de gegenereerde client.  ## 0.5.4 November 2024 - Properties van PagineringResultaat en PagineerbaarResultaat welke altijd aanwezig zullen zijn bij een list-request required gemaakt. - Required properties van put-message-antwoord gecorrigeerd. - Schema van het Null bericht gecorrigeerd.  ## 0.5.3 November 2024 - Het Sv11 bericht is qua schema aangepast aangezien deze onterecht de property plData bevatte. Deze property is verwijderd uit dit bericht. - Foutsituaties zijn voorzien van discriminators ten behoeve van het onderscheiden van foutsituatie subtypes door de gegenereerde client.  ## 0.5.2 Oktober 2024 - De request die volledig afgekeurd worden en een statuscode 4xx of 5xx retourneren, doen dit nu met de response header 'Content-Type: application/problem+json'. - Requests die een 2xx response in JSON formaat retourneren, doen dit met \"Content-Type: application/json\" ipv \"Content-Type: application/json: charset=utf-8\". Conform rfc8259 (https://www.rfc-editor.org/rfc/rfc8259) is JSON altijd in UTF-8 formaat en heeft dit type geen charset parameter.  ## 0.5.1 Oktober 2024  - De fout BBA-PUT-F002 is aangepast naar een algemene fout voor onjuiste velden in een PutMessage, via het veld \"invalidParams\" in de response word aangegeven welke velden onjuist zijn en waarom.  ## 0.5.0 September 2024  - Het veld berichtId en verwijzingBerichtId zijn omgezet van type 'integer' naar type 'string' om beter aan te sluiten op de bestaande voorziening.  - Het probleem-antwoord response object is overal vervangen met de algemene Foutmelding response welke zich conformeert aan RFC7807.  - De velden 'foutTitel', 'foutType', 'foutDetail' zijn aangepast naar 'title, 'type', 'detail' zodat zij zich conformeren aan de RFC7807.  - De afhankelijkheid op 'openapi-problem-detail-v1.yml' is komen te vervallen (https://github.com/rvig-brp/BRP-Berichten-API/issues/3).  ## 0.4.1 Juli 2024  - Het json-schema voor de autorisatieberichten Ct01, Cw01 en Cb01 is toegevoegd.  - De ontvanger is opgenomen in de response bij het verzenden van een bericht. Dit is met name relevant wanneer er een bericht naar een berichtgroep gestuurd wordt. In dat geval weet de verzender wie de uiteindelijke ontvangers zijn. Bij het versturen van een bericht naar de een regulier account zal dit nummer 1:1 overeenkomen met de ontvanger die bij het te verzenden bericht is opgegeven.  ## 0.4.0 Juni 2024 - De json-schema's van de berichtsoorten zijn opgenomen in de OpenAPI Specificatie. Voor elke berichtsoort die het LO beschrijft, is opgenomen hoe dit bericht gestructureerd is.   - Houdt er rekening mee dat het weergeven van de OpenAPI specificatie in de web-versie va SwaggerUI hierdoor trager geworden is. Het is aan te raden om de alternatieve (redocly) weergave te gebruiken:     - https://brp-berichten-api.dictua.ictu-sr.nl/openapi/berichten-api.html     - De JSON schema's zijn tevens te vinden op onze Github pagina. - De JSON-response van het conversie endpoint is iets aangepast zodat naast het geconverteerde bericht tevens validatiefouten opgenomen kunnen worden.  ## 0.3.0 - Mei 2024 - Conversie endpoints   - Introductie bericht-conversie (/berichten/conversie) endpoint. Houdt er rekening mee dat de conversie naar JSON opgenomen is, maar nog niet geïmplementeerd is in de demo omgeving. - Het limiet van het aantal berichten dat verwijderd kan worden is gelijkgesteld aan dat wat gelijktijdig opgehaald kan worden (100). - De API is hernoemd van \"BRP A-Synchrone berichten API\" naar \"BRP berichten API\".   - Nieuwe URL's demo omgeving:     - https://brp-berichten-api.dictua.ictu-sr.nl/api/v1/berichten     - https://brp-berichten-api.dictua.ictu-sr.nl/openapi/berichten-api.html     - https://brp-berichten-api.dictua.ictu-sr.nl/swagger-ui/index.html - Beschikbaarheid endpoint(s)   - Er is een tweede ping endpoint bijgekomen waardoor en nu een HEAD of een GET gedaan kan worden. De response blijft hetzelfde. U kunt zelf kiezen welke van deze twee u hanteert.   - De noodzaak voor authenticatie op het `ping` endpoint is komen te vervallen. U kunt dus zonder noodzaak van authenticatie vaststellen of de dienst beschikbaar is.  ## 0.2.2 - April 2024 - Ping operatie toegevoegd t.b.v. het verifiëren dat er communicatie met de berichtendienst mogelijks is. - De standaard sortering bij een LIST operatie is op dit moment:   1. `Datum + tijdstip van ontvangst` waarbij geldt dat het oudste bericht als eerste wordt weergegeven in de lijst met beschikbare berichten (rationale deze dient als eerste verwerkt worden door de ontvanger).   2. Indien `datum + tijdstip van ontvangst` gelijk zijn (wat kan voorkomen aangezien er meerdere berichten tegelijk ingestuurd kunnen worden), dan worden `afzender` en het `messageId` meegenomen in de sortering. De volgorde die de afzender toegekend heen via de messageId is op dat moment dus bepalend.  ## 0.2.1 - April 2024 - Mogelijkheden tot sortering bij een list operatie zijn verwijderd. De standaard sortering wordt nog bepaald. - Demo omgeving is toegevoegd aan de lijst met servers.   - API te benaderen via https://brp-berichten-api.dictua.ictu-sr.nl/api/v1/berichten   - Swagger UI via: https://brp-berichten-api.dictua.ictu-sr.nl/swagger-ui/index.html   - De OpenAPI specificatie via: https://brp-berichten-api.dictua.ictu-sr.nl/openapi.brp-berichten-api-v1.yaml - Wachtwoord wijzigingen optie is verwijderd. - Het `berichtFormaat` attribuut is komen te vervallen. Alle berichten zijn nu per definitie in JSON formaat. De eis om de berichtInhoud Base64 te   encoderen komt daarmee te vervallen. - Voorbeelddata verbeterd. - Tellingen endpoint toegevoegd welke invulling geeft aan de mailbox Summarize tegenhanger. - Delete endpoint gecorrigeerd. De collectie `succesvolVerwijderdeBerichten` was van het type string i.p.v. berichtTransportId. - Limieten zijn gewijzigd:   - Het aantal berichten dat via een PUT verstuurd kan worden is verhoogd naar 25. Uitgaande van een gemiddelde berichtgrootte van 40kb geeft dat een request van 1MB groot.   - Het aantal berichten dat via een LIST opgevraagd kan worden is vergroot naar 2000. Daarbij krijgt u de mogelijkheid om dit aantal te beperken.     - 2000 berichten in een LIST operatie komt neer op ongeveer 600KB response grootte.   - Het aantal berichten dat via een GET ontvangen kan worden is verhoogd naar 100. Dit heeft te maken met de gangbare (veilige) restricties van een URL qua lengte (2KB).     - Voor de URL worden 256 bytes gereserveerd.       - Voor de UUID blijven dan 1.792 bytes over.     - Een BerichtTransportId is 17 bytes groot (UUID + separatie-karakter ',')       - Uitgaande van 17 bytes, zou dit 105 keer herhaald kunnen worden. Om aan de veilige kan te zitten en om op een mooi rond getal uit te komen kiezen wij voor 100 als limiet.     - Uitgaande van een gemiddelde berichtgrootte van 40KB komt je met 100 berichten uit op 4MB qua response-grootte. - \"aantalKeerOpgehaald\" en \"dtLaatstOpgehaald\" zijn verwijderd uit response van LIST (ListMessageKenmerken schema). Wij zien hierin geen meerwaarde voor de aansluitende partijen. Wel kunt u blijven zien OF het bericht is opgehaald (boolean waarde).  ## 0.2.0 - April 2024 - \"List\" verzoek is verhuisd van \"/berichten/lijst\" --> \"/berichten\" - \"GET\" van meerdere berichten wordt gedaan middels path-parameters i.p.v. query-parameters en is samengevoegd met het endpoint voor het ophalen van een enkel bericht.<br/>   (/berichten/?berichtTransportIds=[UUID],[UUID] --> /berichten/[UUID],[UUID])   (/berichten/?berichtTransportIds=[UUID],[UUID] --> /berichten/[UUID],[UUID]) - \"DELETE\" van meerdere berichten wordt gedaan middels path-parameters i.p.v. query-parameters en is samengevoegd met het endpoint voor het verwijderen van een enkel bericht.<br/>   (/berichten/?berichtTransportIds=[UUID],[UUID] --> /berichten/[UUID],[UUID]) - Het \"berichtId\" wat correspondeert met het \"MessageId\" veld van de mailboxserver is qua type gewijzigd van String naar Integer. Maximale lengte 12.   - Beschrijving LO: MessageId, lengte: 12, Het unieke volgnummer dat aan het uitgaande bericht wordt toegekend. - Het veld \"verwijzingBerichtId\" wat correspondeert met het \"CrossReference\" veld van de mailboxserver:   - is qua type gewijzigd van String naar Integer. Maximale lengte 12.   - kan of weggelaten worden, of gevuld worden met 0 indien het bericht een eerste bericht in de cyclus betreft. - \"aantalKeerOpgehaald\" is toegevoegd aan de ListMessageKenmerken.  ## 0.1.0 - Maart 2024 Initiële versie.  # In ontwikkeling: - Bepalen of het een checksum op de berichtinhoud van meerwaarde kan zijn.  # Voorlopige limieten: | Waarde | Omschrijving | |--------|--------------| | 1      | Aantal ontvangers per bericht. | | 25     | Maximum aantal berichten dat in één PUT request verstuurd mag worden. | | 100     | Maximum aantal berichten dat in één DELETE request verwijderd mag worden | | 2000   | Maximum aantal berichten dat in één LIST request getoond zal worden. Indien wenselijk kunt u dit aantal middels een query-parameter beperken. | | 100    | Maximum aantal berichten dat in één GET request ontvangen mag worden. | | 64kb   | Maximum grootte van één enkel bericht. Één request zal qua grootte dan uitkomen op ((maximale-grootte-enkel-bericht * maximaal-aantal-berichten) + overhead). Houdt er rekening mee dat dit een waarde is die in te toekomst kan gaan groeien. Beperk uw oplossing dus niet op deze waarde! | 

    The version of the OpenAPI document: 0.6.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from berichten_api.models.af01 import Af01
from berichten_api.models.af01_pl_data import Af01PlData
from berichten_api.models.af01_pl_data_c01_inner import Af01PlDataC01Inner
from berichten_api.models.af01_pl_data_c01_inner_all_of_historie_inner import Af01PlDataC01InnerAllOfHistorieInner
from berichten_api.models.af01_pl_data_c02_inner import Af01PlDataC02Inner
from berichten_api.models.af01_pl_data_c02_inner_all_of_historie_inner import Af01PlDataC02InnerAllOfHistorieInner
from berichten_api.models.af01_pl_data_c04_inner import Af01PlDataC04Inner
from berichten_api.models.af01_pl_data_c04_inner_all_of_historie_inner import Af01PlDataC04InnerAllOfHistorieInner
from berichten_api.models.af01_pl_data_c05_inner import Af01PlDataC05Inner
from berichten_api.models.af01_pl_data_c05_inner_all_of_historie_inner import Af01PlDataC05InnerAllOfHistorieInner
from berichten_api.models.af01_pl_data_c06_inner import Af01PlDataC06Inner
from berichten_api.models.af01_pl_data_c06_inner_all_of_historie_inner import Af01PlDataC06InnerAllOfHistorieInner
from berichten_api.models.af01_pl_data_c07_inner import Af01PlDataC07Inner
from berichten_api.models.af01_pl_data_c07_inner_all_of_historie_inner import Af01PlDataC07InnerAllOfHistorieInner
from berichten_api.models.af01_pl_data_c08_inner import Af01PlDataC08Inner
from berichten_api.models.af01_pl_data_c08_inner_all_of_historie_inner import Af01PlDataC08InnerAllOfHistorieInner
from berichten_api.models.af01_pl_data_c09_inner import Af01PlDataC09Inner
from berichten_api.models.af01_pl_data_c09_inner_all_of_historie_inner import Af01PlDataC09InnerAllOfHistorieInner
from berichten_api.models.af01_pl_data_c10_inner import Af01PlDataC10Inner
from berichten_api.models.af01_pl_data_c10_inner_all_of_historie_inner import Af01PlDataC10InnerAllOfHistorieInner
from berichten_api.models.af01_pl_data_c11_inner import Af01PlDataC11Inner
from berichten_api.models.af01_pl_data_c11_inner_all_of_historie_inner import Af01PlDataC11InnerAllOfHistorieInner
from berichten_api.models.af01_pl_data_c12_inner import Af01PlDataC12Inner
from berichten_api.models.af01_pl_data_c12_inner_all_of_historie_inner import Af01PlDataC12InnerAllOfHistorieInner
from berichten_api.models.af01_pl_data_c13_inner import Af01PlDataC13Inner
from berichten_api.models.af01_pl_data_c13_inner_all_of_historie_inner import Af01PlDataC13InnerAllOfHistorieInner
from berichten_api.models.af01_pl_data_c14_inner import Af01PlDataC14Inner
from berichten_api.models.af01_pl_data_c14_inner_all_of_historie_inner import Af01PlDataC14InnerAllOfHistorieInner
from berichten_api.models.af01_pl_data_c15_inner import Af01PlDataC15Inner
from berichten_api.models.af01_pl_data_c15_inner_all_of_historie_inner import Af01PlDataC15InnerAllOfHistorieInner
from berichten_api.models.af01_pl_data_c16_inner import Af01PlDataC16Inner
from berichten_api.models.af01_pl_data_c16_inner_all_of_historie_inner import Af01PlDataC16InnerAllOfHistorieInner
from berichten_api.models.af01_pl_data_c17_inner import Af01PlDataC17Inner
from berichten_api.models.af01_pl_data_c17_inner_all_of_historie_inner import Af01PlDataC17InnerAllOfHistorieInner
from berichten_api.models.af01_pl_data_c21_inner import Af01PlDataC21Inner
from berichten_api.models.af01_pl_data_c21_inner_all_of_historie_inner import Af01PlDataC21InnerAllOfHistorieInner
from berichten_api.models.af11 import Af11
from berichten_api.models.ag01 import Ag01
from berichten_api.models.ag11 import Ag11
from berichten_api.models.ag21 import Ag21
from berichten_api.models.ag31 import Ag31
from berichten_api.models.ap01 import Ap01
from berichten_api.models.autorisatietabelregel import Autorisatietabelregel
from berichten_api.models.av01 import Av01
from berichten_api.models.bbaauthf001 import BBAAUTHF001
from berichten_api.models.bbaauthf002 import BBAAUTHF002
from berichten_api.models.bbaconvf001 import BBACONVF001
from berichten_api.models.bbaconvf002 import BBACONVF002
from berichten_api.models.bbaconvf003 import BBACONVF003
from berichten_api.models.bbaconvf004 import BBACONVF004
from berichten_api.models.bbaconvf005 import BBACONVF005
from berichten_api.models.bbaconvf006 import BBACONVF006
from berichten_api.models.bbadeletef001 import BBADELETEF001
from berichten_api.models.bbadeletef002 import BBADELETEF002
from berichten_api.models.bbadeletef003 import BBADELETEF003
from berichten_api.models.bbadeletef004 import BBADELETEF004
from berichten_api.models.bbaf999 import BBAF999
from berichten_api.models.bbagetf001 import BBAGETF001
from berichten_api.models.bbagetf002 import BBAGETF002
from berichten_api.models.bbagetf003 import BBAGETF003
from berichten_api.models.bbagetf004 import BBAGETF004
from berichten_api.models.bbalistf001 import BBALISTF001
from berichten_api.models.bbaputf001 import BBAPUTF001
from berichten_api.models.bbaputf002 import BBAPUTF002
from berichten_api.models.bbaputf003 import BBAPUTF003
from berichten_api.models.bbaputf004 import BBAPUTF004
from berichten_api.models.bbasummarizef001 import BBASUMMARIZEF001
from berichten_api.models.bericht_kenmerken import BerichtKenmerken
from berichten_api.models.cb01 import Cb01
from berichten_api.models.converteer200_response import Converteer200Response
from berichten_api.models.converteer200_response_validatie_fouten_inner import Converteer200ResponseValidatieFoutenInner
from berichten_api.models.converteer400_response import Converteer400Response
from berichten_api.models.converteer406_response import Converteer406Response
from berichten_api.models.converteer415_response import Converteer415Response
from berichten_api.models.ct01 import Ct01
from berichten_api.models.cw01 import Cw01
from berichten_api.models.delete_message_antwoord import DeleteMessageAntwoord
from berichten_api.models.delete_message_antwoord_all_of_foutmeldingen import DeleteMessageAntwoordAllOfFoutmeldingen
from berichten_api.models.delete_message_antwoord_all_of_niet_succesvol_verwijderde_berichten import DeleteMessageAntwoordAllOfNietSuccesvolVerwijderdeBerichten
from berichten_api.models.dt01 import Dt01
from berichten_api.models.dw01 import Dw01
from berichten_api.models.foutmelding import Foutmelding
from berichten_api.models.generiek_antwoord import GeneriekAntwoord
from berichten_api.models.get_message_antwoord import GetMessageAntwoord
from berichten_api.models.get_message_antwoord_all_of_foutmeldingen import GetMessageAntwoordAllOfFoutmeldingen
from berichten_api.models.get_message_antwoord_all_of_niet_opgehaalde_berichten import GetMessageAntwoordAllOfNietOpgehaaldeBerichten
from berichten_api.models.get_message_antwoord_all_of_opgehaalde_berichten import GetMessageAntwoordAllOfOpgehaaldeBerichten
from berichten_api.models.get_message_kenmerken import GetMessageKenmerken
from berichten_api.models.gv01 import Gv01
from berichten_api.models.gv02 import Gv02
from berichten_api.models.ha01 import Ha01
from berichten_api.models.hf01 import Hf01
from berichten_api.models.hq01 import Hq01
from berichten_api.models.ib01 import Ib01
from berichten_api.models.if01 import If01
from berichten_api.models.if21 import If21
from berichten_api.models.if31 import If31
from berichten_api.models.if41 import If41
from berichten_api.models.ii01 import Ii01
from berichten_api.models.invalid_parameters_inner import InvalidParametersInner
from berichten_api.models.iv01 import Iv01
from berichten_api.models.iv11 import Iv11
from berichten_api.models.iv21 import Iv21
from berichten_api.models.jb01 import Jb01
from berichten_api.models.jf01 import Jf01
from berichten_api.models.jf21 import Jf21
from berichten_api.models.jf31 import Jf31
from berichten_api.models.ji01 import Ji01
from berichten_api.models.jv01 import Jv01
from berichten_api.models.la01 import La01
from berichten_api.models.lf01 import Lf01
from berichten_api.models.lg01 import Lg01
from berichten_api.models.lg01_pl_data import Lg01PlData
from berichten_api.models.list_message_antwoord import ListMessageAntwoord
from berichten_api.models.list_message_kenmerken import ListMessageKenmerken
from berichten_api.models.list_messages401_response import ListMessages401Response
from berichten_api.models.lo_bericht import LoBericht
from berichten_api.models.lq01 import Lq01
from berichten_api.models.ng01 import Ng01
from berichten_api.models.null import Null
from berichten_api.models.of11 import Of11
from berichten_api.models.og11 import Og11
from berichten_api.models.pagineerbaar_resultaat import PagineerbaarResultaat
from berichten_api.models.paginering_resultaat import PagineringResultaat
from berichten_api.models.paginering_verzoek import PagineringVerzoek
from berichten_api.models.pf01 import Pf01
from berichten_api.models.pf02 import Pf02
from berichten_api.models.pf03 import Pf03
from berichten_api.models.put_message import PutMessage
from berichten_api.models.put_message_antwoord import PutMessageAntwoord
from berichten_api.models.put_message_antwoord_all_of_foutmeldingen import PutMessageAntwoordAllOfFoutmeldingen
from berichten_api.models.put_message_antwoord_all_of_niet_verwerkte_berichten import PutMessageAntwoordAllOfNietVerwerkteBerichten
from berichten_api.models.put_message_antwoord_all_of_verwerkte_berichten import PutMessageAntwoordAllOfVerwerkteBerichten
from berichten_api.models.put_message_kenmerken import PutMessageKenmerken
from berichten_api.models.put_message_request import PutMessageRequest
from berichten_api.models.rb01 import Rb01
from berichten_api.models.rf01 import Rf01
from berichten_api.models.rf31 import Rf31
from berichten_api.models.rv01 import Rv01
from berichten_api.models.summarize200_response import Summarize200Response
from berichten_api.models.sv01 import Sv01
from berichten_api.models.sv11 import Sv11
from berichten_api.models.tb01 import Tb01
from berichten_api.models.tb02 import Tb02
from berichten_api.models.tf01 import Tf01
from berichten_api.models.tf11 import Tf11
from berichten_api.models.tf21 import Tf21
from berichten_api.models.tv01 import Tv01
from berichten_api.models.vb01 import Vb01
from berichten_api.models.vb02 import Vb02
from berichten_api.models.wa01 import Wa01
from berichten_api.models.wa11 import Wa11
from berichten_api.models.wf01 import Wf01
from berichten_api.models.xa01 import Xa01
from berichten_api.models.xf01 import Xf01
from berichten_api.models.xq01 import Xq01
